### ISSUE TITLE
About EAWebkit

### ISSUE THREAD

**Issue by hedecai** [ychin/EAWebKit#1]
Hi, is it possible to integrated EAWebkit with OGRE?

**Comment by ychin** [comment]
Maybe, but immediate priority is to write some common wrapper utilities and frameworks around it first to make it easily integrate-able to any engines, then write an example wrapper as a standalone program.

There's also a newer version that will be integrated soon.

So as a result this may have to be on the backburners until I get those parts done first.

**Comment by hedecai** [comment]
I'm look forward for that. If this come to true, there will be a new way to write GUI for games.

**Comment by sloopdoom** [comment]
Eawebkit is great, could you tell us some example or tutorial. there are  few information about it.thanks

**Comment by ychin** [comment]
Unfortunately there isn't a lot of public information on EA WebKit as it's mostly a source dump from http://gpl.ea.com. I can try to see if I can put together some demo app to make it clear how to use it, but I can't really guarantee on the timeline. Feel free to ping me too if you run into issues.

**Comment by bholcomb** [comment]
Thanks for putting this up on github.  I'm working on integrating into several projects.   I sent you an email to your blog email address.  I've got some time to help document and write examples if you can provide some guidance.

cheers, 

Bob

**Comment by rafadsm** [comment]
Thank you very much for hosting this repository with a functional build!
How could I get started with this in my project? I'm currently using CEF, but I'm looking for something more performance
I implemented in my project but I did not find the starting point to start using :(

**Comment by bholcomb** [comment]
I have started building an example of how to integrate EAWebkit into an OpenGL application.  It's commented, but not exactly a tutorial yet.  I do plan on writing the documentation that goes with this to make it a full tutorial. 

check it out at: https://github.com/bholcomb/glWebKit

cheers, 

Bob

**Comment by rafadsm** [comment]
I'll take a look and thank you for sharing with us.

**Comment by ychin** [comment]
@bholcomb Thanks. I don't really have time these days to set up documentation and demo project for EAWebKit, so I appreciate the help.

**Comment by sloopdoom** [comment]
great , thank  a lot!

**Comment by ychin** [comment]
Just closing this. This repo is barely maintained, and I'll mostly just upload mirrored packages up but probably won't do much more than that.
