### ISSUE TITLE
Current mirrored version (16.3.1.1.0) does not build

### ISSUE THREAD

**Issue by ychin** [ychin/EAWebKit#3]

**Comment by jrdpinto** [comment]
Hi there,

Have you had any luck resolving this issue? I'm keen to get this building inside Visual Studio 2017 but I encounter errors trying to load each project because of a missing dependency called "FrameworkMsbuild.props". If you have any advice on how to get around this issue it would be much appreciated.

Thanks.

**Comment by ychin** [comment]
I didn't resolve it, but let me take a look first.

**Comment by MarkusRannare** [comment]
I managed to build it in MSVS 2015, I just opened all vsproj's and removed all references to Framework. A educated guess is that Framework is EA's build system.
Then I needed to move a lot of files in:
WebCore\DerivedSources\ to
WebCore\DerivedSources\pc64\dev-debug (and WebCore\DerivedSources\pc64\dev-opt)
I haven't come around to test it yet

**Comment by jrdpinto** [comment]
Thanks for the feedback. Going to try this myself as soon as I can.

**Comment by ychin** [comment]
I did something similar to @MarkusRannare and managed to build. I had to clean up the Framework references (it's an internal EA tool), convert all the relative paths to Program Files / etc, fix up the Windows SDK versions, and also change all the WebCore\DerivedSources\pc64\dev-debug\* paths to WebCore\DerivedSources.

I'll try to fix this soon and commit a new version that would work. Hopefully their next release will work better.

**Comment by jrdpinto** [comment]
Thanks, much appreciated. Will be evaluating the library for use in a commercial engine. I'll do my best to contribute anything I can if I start working with it.

**Comment by ychin** [comment]
You should be able to build in Windows (both 32 and 64-bit) now. I did update the tools versions to the latest (Visual Studio 2017) and Windows Kit 17134 (see the commit message for 0e07800). Let me know if this doesn't work.

**Comment by jrdpinto** [comment]
Thanks ychin. Will let you know if there are any more issues.
