### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by zbozo** [ychin/EAWebKit#4]
How to make this work in a project? Where to start?

**Comment by bholcomb** [comment]
I have started building an example of how to integrate EAWebkit into an OpenGL application.  It's commented, but not exactly a tutorial yet.  I do plan on writing the documentation that goes with this to make it a full tutorial. 

check it out at: https://github.com/bholcomb/glWebKit

cheers, 

Bob

**Comment by ychin** [comment]
See #1 for the main discussion..
