### ISSUE TITLE
Lets make a simple ui to use eawebkit view websites?

### ISSUE THREAD

**Issue by linsmod** [ychin/EAWebKit#6]

**Comment by ychin** [comment]
I have thought about it before but it's actually a fair bit of work and EAWebKit is mostly working as a mirror repo to EA's version for now so I would not have much time to work on this. I would not mind if someone else spends the time on this though.

**Comment by linsmod** [comment]
its okay,  btw i noticed the gl and dirextx11 sample using eawebkit, may be some help to me.

**Comment by ychin** [comment]
Just closing this. This repo is barely maintained, and I'll probably only upload mirrored content up, but not much more.
